### ISSUE TITLE
Sequoia build can't be opened on Big Sur

### ISSUE THREAD

**Issue by KBLiveSolutions** [Julusian/node-midi#35]
Hi

I am building an app using electron-builder. The app runs fine on my M1 / Sequoia machine, but when i build it as universal and launch the build on a Big Sur machine, I get this error :

```
Uncaught Exception:
Error: dlopen(/Applications/showcontrol.app/Contents/Resources/app.asar.unpacked/node_modules/@julusian/midi/build/Release/midi.node, 1): Symbol not found: __ZTTNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
Referenced from: /Applications/showcontrol.app/Contents/Resources/app.asar.unpacked/node_modules/@julusian/midi/build/Release/midi.node
Expected in: /usr/lib/libc++.1.dylib
in /Applications/showcontrol.app/Contents/Resources/app.asar.unpacked/node_modules/@julusian/midi/build/Release/midi.node
at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
at Module.load (node:internal/modules/cjs/loader:1295:32)
at Module._load (node:internal/modules/cjs/loader:1111:12)
at c._load (node:electron/js2c/node_init:2:17025)
at Module.require (node:internal/modules/cjs/loader:1318:19)
at require (node:internal/modules/helpers:179:18)
at loadBinding (/Applications/showcontrol.app/Contents/Resources/app.asar/node_modules/pkg-prebuilds/bindings.js:103:9)
at Object.<anonymous> (/Applications/showcontrol.app/Contents/Resources/app.asar/node_modules/@julusian/midi/midi.js:1:47)

```
tried with x64 but it didn't help. also tried npx electron-rebuild.
Any idea how to fix that ?
Thanks

**Comment by Julusian** [comment]
Based on the path in that error `/Applications/showcontrol.app/Contents/Resources/app.asar.unpacked/node_modules/@julusian/midi/build/Release/midi.node`, electron-builder recompiled this library.
The prebuilt version of this library is compiled to avoid this runtime error. 

I would suggest either telling electron-builder to not recompile this library (it doesn't need to be recompiled), or you could try setting the environment variable `export MACOSX_DEPLOYMENT_TARGET="10.13"` before performing the build which should make the build work on older macos

**Comment by KBLiveSolutions** [comment]
Thanks for your answer. 
I tried both methods but it didn't work, although I'm not too sure I did it right. 
I eventually installed my code and built it from the Big Sur machine and it worked. 
I'll try to investigate about the Sequoia thing when I find som time.
